const keyName_SavedPost="SavedPost";class DEF_SavedPostEntry{postLink="";imgLinks=[];postDate="2025-1-1"}function ThumbNailLinkCheck(){try{var t=$(".img_thumbnails");console.assert(0<t.length,"Failed: img.length>0",t),t.hide()}catch(t){console.error(t+`.
 `+t.stack)}}function getSavedPostArray(){try{var a=GetPageDate().toISOString().split("T")[0];let e=JSON.parse(localStorage.getItem(keyName_SavedPost));void 0!==e&&null!=e||(e=[]),console.assert(!(void 0===e||null==e),"Failed: !(typeof data_savedPost === undefined)",e);var o=[];for(let t=0;t<e.length;t++){var s=e[t];r=s.postDate,r=new Date(r),(isNaN(r.getTime())||s.postDate==a)&&o.push(s)}return o}catch(t){console.error(t+`.
 `+t.stack)}var r}function removePostInSavedPost(e){try{var a=getSavedPostArray(),o=[];for(let t=0;t<a.length;t++){var s=a[t];s.postLink!=e&&o.push(s)}localStorage.setItem(keyName_SavedPost,JSON.stringify(o))}catch(t){console.error(t+`.
 `+t.stack)}}function ShowNumSavedPost(){try{var a=getSavedPostArray().map(t=>t.postLink);let e=$("#panel_displayContainer").find("a");var o=e.map(t=>$(e[t]).attr("href")),s=new Set(a);let t=0;for(const r of o)s.has(r)&&t++;$(".NumSavedPost").text(t)}catch(t){console.error(t+`.
 `+t.stack)}}function ShowSavedPost(){try{return void ShowNumSavedPost()}catch(t){console.error(t+`.
 `+t.stack)}}function checkLinksExist(){try{function t(t){const e=$(t);var a=e.attr("href");fetch(a).then(t=>{t.ok?e.show():e.hide()}).catch(()=>{$("#"+t).hide()})}t(".link_next_page"),t(".link_previous_page")}catch(t){console.error(t+`.
 `+t.stack)}}function GetPageDate(){try{var t=window.location.pathname,e=t.substring(t.lastIndexOf("/")+1).replace(/\.[^/.]+$/,"").split("_").slice(-3).join("-");return new Date(e)}catch(t){console.error(t+`.
 `+t.stack)}}function AddSavedPost(t){try{console.assert(t instanceof HTMLAnchorElement,"Failed:  (tag_link instanceof HTMLAnchorElement)",t);var e=$(t),a=e.attr("href"),o=e.find("img"),s=(console.assert(0<o.length,"Failed: $imgs.length>0",e),o.map(function(){return $(this).attr("src")}).get()),r=(console.assert(0<s.length,"Failed: imgLinks.length>0",e),new DEF_SavedPostEntry),n=(Object.preventExtensions(r),r.postLink=a,r.imgLinks=s,r.postDate=GetPageDate().toISOString().split("T")[0],keyName_SavedPost in localStorage||localStorage.setItem(keyName_SavedPost,JSON.stringify([])),removePostInSavedPost(r.postLink),getSavedPostArray());n.push(r),localStorage.setItem(keyName_SavedPost,JSON.stringify(n)),ShowSavedPost()}catch(t){console.error(t+`.
 `+t.stack)}}function UpdateSaveButtonColor(t){try{$div_this=$(t),console.assert($div_this.hasClass("entryDiv"),"Failed: $div_this.hasClass(.entryDiv)",t);var e=$div_this.find("a").attr("href"),a=getSavedPostArray();$div_this.find(".saveIcon svg").attr("fill","gray");for(let t=0;t<a.length;t++)if(a[t].postLink==e){$div_this.find(".saveIcon svg").attr("fill","red");break}}catch(t){console.error(t+`.
 `+t.stack)}}function Adjust_EntryDiv(){try{var a=$(".entryContainer .entryDiv");let e=new IntersectionObserver(t=>{t.forEach(t=>{t.isIntersecting&&UpdateSaveButtonColor(t.target)})},{root:null,threshold:.1});a.each(t=>{e.observe(a.get(t)),$("#Icon_Heart").clone().attr({class:"saveIcon"}).removeAttr("id","").appendTo($(a.eq(t))).on("click",function(){$div_this=$(this);var e=$(this).parent().find("a").get(0),a=getSavedPostArray();let o=!1;for(let t=0;t<a.length;t++)if(a[t].postLink==e){o=!0;break}o?(removePostInSavedPost(e),ShowSavedPost()):AddSavedPost(e),UpdateSaveButtonColor($(this).parent())})})}catch(t){console.error(t+`.
 `+t.stack)}}try{ThumbNailLinkCheck(),checkLinksExist(),Adjust_EntryDiv(),ShowSavedPost()}catch(t){console.error(t+`.
 `+t.stack)}