"use strict";const keyName_SavedPost="SavedPost";class DEF_SavedPostEntry{postLink="";imgLinks=[];postDate="";HasPostDateInfo=function(){try{console.assert(this instanceof DEF_SavedPostEntry,"Failed: this instanceof def_SavedPostEntry",this);var t=new Date(this.postDate);return!isNaN(t.getTime())}catch(t){console.error(t+`.
 `+t.stack)}};IsValid=function(){try{return""!==this.postLink.trim()&&0<this.imgLinks.length}catch(t){console.error(t+`.
 `+t.stack)}}}function ThumbNailLinkCheck(){try{var t=$(".img_thumbnails");console.assert(0<t.length,"Failed: img.length>0",t),t.hide()}catch(t){console.error(t+`.
 `+t.stack)}}function getSavedPostArray(){try{GetPageDate().toISOString().split("T")[0];let t=JSON.parse(localStorage.getItem(keyName_SavedPost));return void 0!==t&&null!=t||(t=[]),console.assert(!(void 0===t||null==t),"Failed: !(typeof data_savedPost === undefined)",t),t}catch(t){console.error(t+`.
 `+t.stack)}}function removePostInSavedPost(e){try{var o=getSavedPostArray(),a=[];for(let t=0;t<o.length;t++){var s=o[t];s.postLink!=e&&a.push(s)}localStorage.setItem(keyName_SavedPost,JSON.stringify(a))}catch(t){console.error(t+`.
 `+t.stack)}}function ShowNumSavedPost(){try{var o=getSavedPostArray().map(t=>t.postLink);let e=$("#panel_displayContainer").find("a");var a=e.map(t=>$(e[t]).attr("href")),s=new Set(o);let t=0;for(const n of a)s.has(n)&&t++;$(".NumSavedPost").text(t)}catch(t){console.error(t+`.
 `+t.stack)}}function ShowSavedPost(){try{return void ShowNumSavedPost()}catch(t){console.error(t+`.
 `+t.stack)}}function CheckSavedPostDateInfo(){try{console.log("CheckSavedPostDateInfo");var t=getSavedPostArray(),o=t.length;let e=$("#panel_displayContainer").find("a");var a,s=e.map(t=>$(e[t]).attr("href")),n=GetPageDate(),r=new Set(s),c=[];for(a of t){console.log("raw",a);var i=new DEF_SavedPostEntry;Object.assign(i,a),!r.has(i.postLink)||i.HasPostDateInfo()||(i.postDate=n),console.assert(i.IsValid(),"Failed: savedPost_new.IsValid()",i),i.IsValid()&&c.push(i)}console.assert(c.length==o,`Failed: newResult.length(${c.length})== count_before(${o})`),console.log("newResult",c),localStorage.setItem(keyName_SavedPost,JSON.stringify(c))}catch(t){console.error(t+`.
 `+t.stack)}}function checkLinksExist(){try{function t(t){const e=$(t);var o=e.attr("href");fetch(o).then(t=>{t.ok?e.show():e.hide()}).catch(()=>{$("#"+t).hide()})}t(".link_next_page"),t(".link_previous_page")}catch(t){console.error(t+`.
 `+t.stack)}}function GetPageDate(){try{var t=window.location.pathname,e=t.substring(t.lastIndexOf("/")+1).replace(/\.[^/.]+$/,"").split("_").slice(-3).join("-");return new Date(e)}catch(t){console.error(t+`.
 `+t.stack)}}function AddSavedPost(t){try{console.assert(t instanceof HTMLAnchorElement,"Failed:  (tag_link instanceof HTMLAnchorElement)",t);var e=$(t),o=e.attr("href"),a=e.find("img"),s=(console.assert(0<a.length,"Failed: $imgs.length>0",e),a.map(function(){return $(this).attr("src")}).get()),n=(console.assert(0<s.length,"Failed: imgLinks.length>0",e),new DEF_SavedPostEntry),r=(Object.preventExtensions(n),n.postLink=o,n.imgLinks=s,n.postDate="",console.log("add post",n),keyName_SavedPost in localStorage||localStorage.setItem(keyName_SavedPost,JSON.stringify([])),removePostInSavedPost(n.postLink),getSavedPostArray());r.push(n),localStorage.setItem(keyName_SavedPost,JSON.stringify(r)),ShowSavedPost()}catch(t){console.error(t+`.
 `+t.stack)}}function DisplaySaveButtonColor(t){try{console.assert(t instanceof Object,"Failed: entryDiv instaceof Object",t);var e=$(t),o=(console.assert(e.hasClass("entryDiv"),"Failed: $div_this.hasClass(.entryDiv)",t),e.find("a").attr("href")),a=getSavedPostArray();e.find(".saveIcon svg").attr("fill","gray");for(let t=0;t<a.length;t++)if(a[t].postLink==o){e.find(".saveIcon svg").attr("fill","red");break}}catch(t){console.error(t+`.
 `+t.stack)}}function Adjust_EntryDiv(){try{var o=$(".entryContainer .entryDiv");let e=new IntersectionObserver(t=>{t.forEach(t=>{t.isIntersecting&&DisplaySaveButtonColor(t.target)})},{root:null,threshold:.1});o.each(t=>{e.observe(o.get(t)),$("#Icon_Heart").clone().attr({class:"saveIcon"}).removeAttr("id","").appendTo($(o.eq(t))).on("click",function(){var e=$(this).parent().find("a").get(0),o=getSavedPostArray();let a=!1;for(let t=0;t<o.length;t++){var s=o[t];if(s.postLink==e){a=!0,console.log("isSavePost",s);var n=new DEF_SavedPostEntry;Object.assign(n,s),console.log("newObj.HasPostDateInfo()",n.HasPostDateInfo()),n.HasPostDateInfo()||CheckSavedPostDateInfo();break}}a?(console.log("remove"),removePostInSavedPost(e),ShowSavedPost()):(console.log("add"),AddSavedPost(e)),DisplaySaveButtonColor($(this).parent())})})}catch(t){console.error(t+`.
 `+t.stack)}}try{ThumbNailLinkCheck(),checkLinksExist(),Adjust_EntryDiv(),ShowSavedPost()}catch(t){console.error(t+`.
 `+t.stack)}